name: test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "18"]
    name: node ${{ matrix.node }}
    env:
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install ${{ matrix.node }}  node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test
