name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: Node ${{ matrix.node }} test
    env:
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install ${{ matrix.node }}  node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test
